pipeline {
  agent any
  
  parameters {
    string(name: 'build_version', defaultValue: 'V1.0', description: 'Version de l\'image Docker')
  }
  
  stages {
    // Jenkins fait le checkout automatiquement. 
    // On commence par vérifier que ta machine est bien en Java 17.
    stage('Initialisation') {
      steps {
        sh 'java -version'
        sh 'mvn -version'
      }
    }
    
    stage('Build and Test') {
      steps {
        // Compilation du projet Java avec Maven
        sh 'cd demo-java-app && mvn clean package'
      }
    }
    
    stage('Static Code Analysis') {
      environment {
        SONAR_URL = "http://sonarqube:9000"
      }
      steps {
        withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
          sh 'cd demo-java-app && mvn sonar:sonar -Dsonar.login=$SONAR_AUTH_TOKEN -Dsonar.host.url=${SONAR_URL}'
        }
      }
    }
    
    stage('Build and Push Docker Image') {
      environment {
        // Utilisation de ton compte DockerHub cheikhdou40
        DOCKER_IMAGE = "cheikhdou40/demo-java-app:${build_version}"
      }
      steps {
        script {
            // Construction de l'image Docker
            sh 'cd demo-java-app && docker build -t ${DOCKER_IMAGE} . '
            
            // Push vers DockerHub
            def dockerImage = docker.image("${DOCKER_IMAGE}")
            docker.withRegistry('https://index.docker.io/v1/', "dockerhub") {
                dockerImage.push()
            }
        }
      }
    }
    
    stage('Update Deployment File') {
        environment {
            GIT_REPO_NAME = "devops-demo-project"
            GIT_USER_NAME = "cheikhdou40"
        }
        steps {
            // On utilise l'ID de credential 'cheikhdou40' pour GitHub
            withCredentials([string(credentialsId: 'cheikhdou40', variable: 'GITHUB_TOKEN')]) {
                sh """
                    git config user.email "cheikhdou40@gmail.com"
                    git config user.name "cheikhdou40"
                    sed -i 's/tag: .*/tag: "${build_version}"/' helm/app/values.yaml
                    git add helm/app/values.yaml
                    git commit -m "Update deployment image to version ${build_version}"
                    git push https://${GITHUB_TOKEN}@github.com/cheikhdieng40/${GIT_REPO_NAME} HEAD:main
                """
            }
        }
    }
  }
}
