pipeline {
  agent any
  parameters {
    string(name: 'build_version', defaultValue: 'V1.0', description: 'Version Docker')
  }
  stages {
    stage('Build and Test') {
      steps {
        sh 'cd demo-java-app && mvn clean package'
      }
    }
    stage('Static Code Analysis') {
      steps {
        withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
          sh 'cd demo-java-app && mvn sonar:sonar -Dsonar.login=$SONAR_AUTH_TOKEN -Dsonar.host.url=http://sonarqube:9000'
        }
      }
    }
    stage('Build and Push Docker Image') {
      environment {
        DOCKER_IMAGE = "cheikhdou40/demo-java-app:${build_version}"
      }
      steps {
        script {
            sh 'cd demo-java-app && docker build -t ${DOCKER_IMAGE} .'
            docker.withRegistry('https://index.docker.io/v1/', "dockerhub") {
                docker.image("${DOCKER_IMAGE}").push()
            }
        }
      }
    }
    stage('Update Deployment File') {
        steps {
            withCredentials([string(credentialsId: 'cheikhdou40', variable: 'GITHUB_TOKEN')]) {
                sh """
                    git config user.email "cheikhdou40@gmail.com"
                    git config user.name "cheikhdou40"
                    sed -i 's/tag: .*/tag: "${build_version}"/' helm/app/values.yaml
                    git add helm/app/values.yaml
                    git commit -m "Update version ${build_version}"
                    git push https://${GITHUB_TOKEN}@github.com/cheikhdieng40/devops-demo-project.git HEAD:main
                """
            }
        }
    }
  }
}
